from bot import CMD_INDEX


class _BotCommands:
    def __init__(self):
        self.StartCommand = f'jstart{CMD_INDEX}'
        self.MirrorCommand = f'jmirror{CMD_INDEX}'
        self.UnzipMirrorCommand = f'junzipmirror{CMD_INDEX}'
        self.ZipMirrorCommand = f'jzipmirror{CMD_INDEX}'
        self.CancelMirror = f'jcancel{CMD_INDEX}'
        self.CancelAllCommand = f'jcancelall{CMD_INDEX}'
        self.ListCommand = f'jlist{CMD_INDEX}'
        self.SearchCommand = f'jsearch{CMD_INDEX}'
        self.StatusCommand = f'jstatus{CMD_INDEX}'
        self.AuthorizedUsersCommand = f'jusers{CMD_INDEX}'
        self.AuthorizeCommand = f'jauthorize{CMD_INDEX}'
        self.UnAuthorizeCommand = f'junauthorize{CMD_INDEX}'
        self.AddSudoCommand = f'jaddsudo{CMD_INDEX}'
        self.RmSudoCommand = f'jrmsudo{CMD_INDEX}'
        self.PingCommand = f'jping{CMD_INDEX}'
        self.RestartCommand = f'jrestart{CMD_INDEX}'
        self.StatsCommand = f'jstats{CMD_INDEX}'
        self.HelpCommand = f'jhelp{CMD_INDEX}'
        self.LogCommand = f'jlog{CMD_INDEX}'
        self.SpeedCommand = f'jspeedtest{CMD_INDEX}'
        self.CloneCommand = f'jclone{CMD_INDEX}'
        self.CountCommand = f'jcount{CMD_INDEX}'
        self.WatchCommand = f'jwatch{CMD_INDEX}'
        self.ZipWatchCommand = f'jzipwatch{CMD_INDEX}'
        self.QbMirrorCommand = f'jqbmirror{CMD_INDEX}'
        self.QbUnzipMirrorCommand = f'jqbunzipmirror{CMD_INDEX}'
        self.QbZipMirrorCommand = f'jqbzipmirror{CMD_INDEX}'
        self.DeleteCommand = f'jdel{CMD_INDEX}'
        self.ShellCommand = f'jshell{CMD_INDEX}'
        self.ExecHelpCommand = f'jexechelp{CMD_INDEX}'
        self.LeechSetCommand = f'jleechset{CMD_INDEX}'
        self.SetThumbCommand = f'jsetthumb{CMD_INDEX}'
        self.LeechCommand = f'jleech{CMD_INDEX}'
        self.UnzipLeechCommand = f'junzipleech{CMD_INDEX}'
        self.ZipLeechCommand = f'jzipleech{CMD_INDEX}'
        self.QbLeechCommand = f'jqbleech{CMD_INDEX}'
        self.QbUnzipLeechCommand = f'jqbunzipleech{CMD_INDEX}'
        self.QbZipLeechCommand = f'jqbzipleech{CMD_INDEX}'
        self.LeechWatchCommand = f'jleechwatch{CMD_INDEX}'
        self.LeechZipWatchCommand = f'jleechzipwatch{CMD_INDEX}'
        self.RssListCommand = f'jrsslist{CMD_INDEX}'
        self.RssGetCommand = f'jrssget{CMD_INDEX}'
        self.RssSubCommand = f'jrsssub{CMD_INDEX}'
        self.RssUnSubCommand = f'jrssunsub{CMD_INDEX}'
        self.RssUnSubAllCommand = f'jrssunsuball{CMD_INDEX}'

BotCommands = _BotCommands()
